export const FROM_WAITING_FOR_DEVELOPMENT_TO_IN_PROGRESS = 1;
export const FROM_IN_PROGRESS_TO_IN_REVIEW = 3;
export const FROM_IN_REVIEW_TO_READY_FOR_TESTING = 5;
export const FROM_READY_FOR_TESTING_TO_IN_TESTING = 7;
export const FROM_IN_TESTING_TO_READY_TO_RELEASE = 9;

export const FROM_WAITING_FOR_DEVELOPMENT_TO_IN_PROGRESS_COLOR = "red";
export const FROM_IN_PROGRESS_TO_IN_REVIEW_COLOR = "green"
export const FROM_IN_REVIEW_TO_READY_FOR_TESTING_COLOR = "yellow"
export const FROM_READY_FOR_TESTING_TO_IN_TESTING_COLOR = "pink"
export const FROM_IN_TESTING_TO_READY_TO_RELEASE_COLOR = "blue";